protoc: ../from_protoc/model_e1.pb.cc ../from_protoc/model_e2.pb.cc ../from_protoc/model_e3.pb.cc ../from_protoc/model_e4.pb.cc ../from_protoc/model_astro.pb.cc
../from_protoc/%.pb.cc: ../%.proto
	protoc -I../ --cpp_out=../from_protoc "$<"
